const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND_STATUS = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST, UNAUTHORIZED, NOT_FOUND_STATUS, INTERNAL_SERVER_ERROR,
};
